### ISSUE TITLE
Phase 2: Implementing Filter Bank

### ISSUE THREAD

**Issue by danryanhuynh** [Danryanh7/SYDE_252_Signals_Processing#2]
# Overview
## Task 4
Design a bank of bandpass filters that filters (splits) the sound to N frequency bands between 100 Hz and 8 kHz. These N frequency bands represent the N channels distributed along the length of the cochlear implant.

***Suggestion:*** Think about your choices for the number of channels (N) and how you want to distribute the frequency range among the channels.

The Matlab filter examples in your book can give you some ideas. Matlab has some filter design tools that you can use also (e.g., filterDesigner).

Here are some example choices to consider in your design:

IIR vs FIR filters
Various filter types

***Hint:*** If you use one of the Matlab built-in filters, pay attention to the normalized frequency (π radian/sample) vs the physical frequency in Hz. To convert Hz to normalized frequency divide it to half the sampling rate and vice versa.
Suggestion: Instead of repeatedly typing commands for channels, try to define your filters in a function and call the function with different parameters and bands in for loops.

## TODOs

- [x] Choose a type of bandpass filter
- [x] Choose N channels (add more to this task list for task 4 (ask about on Nov 6 2023)
- [x] Research into how the FIR filter works and how to implement using Python
