### ISSUE TITLE
Phase 2: Applications of Task 4

### ISSUE THREAD

**Issue by danryanhuynh** [Danryanh7/SYDE_252_Signals_Processing#4]
# Overview
Using the band pass filter from task 4 to perform signals processing.
## TODOs
- [x] Task 5: Filter the sound with the passband bank. (Dan)
- [x] Task 6: Plot the output signals of the lowest and highest frequency channels. (Dan)
- [ ] Task 7: Envelop extraction step 1: rectify the output signals of all bandpass filters. (Hint: Use abs)
- [ ] Task 8: Envelop extraction step 2: detect the envelopes of all rectified signals using a lowpass filter with 400 Hz cutoff.
- [ ] Task 9: Plot the extracted envelope of the lowest and highest frequency channels.
